import { createClientFromRequest } from 'npm:@base44/sdk@0.8.23';

// SHA-256 hash of a string using Web Crypto API
async function sha256(text) {
  const encoder = new TextEncoder();
  const data = encoder.encode(text);
  const hashBuffer = await crypto.subtle.digest('SHA-256', data);
  const hashArray = Array.from(new Uint8Array(hashBuffer));
  return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
}

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();
    if (!user || user.role !== 'admin') {
      return Response.json({ error: 'Forbidden' }, { status: 403 });
    }

    const { draft_id } = await req.json();

    const draft = await base44.asServiceRole.entities.PaperDraft.get(draft_id);
    if (!draft) return Response.json({ error: 'Draft not found' }, { status: 404 });

    const sections = draft.sections || {};
    const timestampUtc = new Date().toISOString();

    // Hash each section individually
    const sectionsFingerprint = {};
    for (const [key, value] of Object.entries(sections)) {
      if (value) sectionsFingerprint[key] = await sha256(value);
    }

    // Master hash: full concatenated content + title + timestamp + author
    const masterContent = [
      draft.title || '',
      sections.abstract || '',
      sections.introduction || '',
      sections.methods || '',
      sections.results || '',
      sections.discussion || '',
      sections.conclusion || '',
      sections.references || '',
      timestampUtc,
      user.email,
    ].join('\n---\n');

    const contentHash = await sha256(masterContent);

    const certificate = `AUTHORSHIP CERTIFICATE
======================
Title: ${draft.title}
Genus: ${draft.genus}
Author: ${user.email}
Timestamp (UTC): ${timestampUtc}
SHA-256 Hash: ${contentHash}
Words: ~${draft.word_count?.toLocaleString() || 'unknown'}

This certificate records that the above content existed in this exact form
at the stated timestamp. The hash may be independently verified against
the stored content to prove priority of creation.

Generated by DataWinder Academic Paper Lab.
Under UK law, copyright subsists automatically in original literary works
from the moment of creation (Copyright, Designs and Patents Act 1988).`;

    const record = await base44.asServiceRole.entities.AuthorshipRecord.create({
      draft_id,
      paper_title: draft.title,
      genus: draft.genus,
      content_hash: contentHash,
      word_count: draft.word_count,
      author_email: user.email,
      timestamp_utc: timestampUtc,
      certificate_text: certificate,
      sections_fingerprint: sectionsFingerprint,
    });

    console.log(`[AUTHORSHIP] Registered: ${contentHash} for "${draft.title}" by ${user.email} at ${timestampUtc}`);

    return Response.json({
      status: 'registered',
      record_id: record.id,
      content_hash: contentHash,
      timestamp_utc: timestampUtc,
      certificate_text: certificate,
    });
  } catch (err) {
    console.error(err);
    return Response.json({ error: err.message }, { status: 500 });
  }
});