import { createClientFromRequest } from 'npm:@base44/sdk@0.8.23';

Deno.serve(async (req) => {
  try {
    const base44 = createClientFromRequest(req);
    const user = await base44.auth.me();

    if (!user) {
      return Response.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { species_ids, report_name } = await req.json();

    if (!species_ids || !Array.isArray(species_ids) || species_ids.length === 0) {
      return Response.json({ error: 'No species provided' }, { status: 400 });
    }

    // Fetch species data
    const speciesData = await Promise.all(
      species_ids.map(id => base44.asServiceRole.entities.Species.get(id))
    );

    const metrics = calculateMetrics(speciesData);
    const title = report_name || 'Multi-Species Conservation Report';
    const generatedAt = new Date().toLocaleString('en-GB');

    // Build HTML report
    const html = `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>${escHtml(title)}</title>
<style>
  * { box-sizing: border-box; margin: 0; padding: 0; }
  body { font-family: Arial, sans-serif; font-size: 12px; color: #1a1a1a; background: #fff; }
  .header { background: #c62335; color: #fff; padding: 24px 32px; }
  .header h1 { font-size: 22px; margin-bottom: 4px; }
  .header p { font-size: 11px; opacity: 0.85; }
  .section { padding: 20px 32px; border-bottom: 1px solid #e5e7eb; }
  .section h2 { font-size: 14px; font-weight: bold; color: #c62335; margin-bottom: 12px; border-left: 4px solid #c62335; padding-left: 8px; }
  .summary-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin-bottom: 8px; }
  .metric-box { background: #f8f8f8; border: 1px solid #e5e7eb; border-radius: 6px; padding: 12px; text-align: center; }
  .metric-box .num { font-size: 26px; font-weight: bold; color: #c62335; }
  .metric-box .lbl { font-size: 10px; color: #6b7280; margin-top: 2px; }
  table { width: 100%; border-collapse: collapse; font-size: 11px; }
  th { background: #c62335; color: #fff; padding: 6px 8px; text-align: left; }
  td { padding: 5px 8px; border-bottom: 1px solid #e5e7eb; }
  tr:nth-child(even) td { background: #f9fafb; }
  .status-badge { display: inline-block; padding: 2px 7px; border-radius: 4px; font-size: 10px; font-weight: bold; color: #fff; }
  .status-CR { background: #b91c1c; }
  .status-EN { background: #c2410c; }
  .status-VU { background: #b45309; }
  .status-NT { background: #92400e; }
  .status-LC { background: #15803d; }
  .status-DD { background: #475569; }
  .status-NE { background: #6b7280; }
  .footer { padding: 16px 32px; font-size: 10px; color: #9ca3af; text-align: center; }
</style>
</head>
<body>

<div class="header">
  <h1>${escHtml(title)}</h1>
  <p>Generated by DataWinder &bull; ${generatedAt} &bull; ${speciesData.length} species assessed</p>
</div>

<div class="section">
  <h2>Executive Summary</h2>
  <div class="summary-grid">
    <div class="metric-box"><div class="num">${speciesData.length}</div><div class="lbl">Species Assessed</div></div>
    <div class="metric-box"><div class="num">${metrics.totalObservations.toLocaleString()}</div><div class="lbl">Total Observations</div></div>
    <div class="metric-box"><div class="num">${metrics.statusBreakdown.CR + metrics.statusBreakdown.EN}</div><div class="lbl">CR + EN Species</div></div>
    <div class="metric-box"><div class="num">${metrics.populationTrend.decreasingCount}</div><div class="lbl">Declining Populations</div></div>
    <div class="metric-box"><div class="num">${metrics.dataGaps}</div><div class="lbl">Data Gaps</div></div>
    <div class="metric-box"><div class="num">${speciesData.filter(s => s.iucn_status && s.iucn_status !== 'NE').length}</div><div class="lbl">IUCN Assessed</div></div>
  </div>
  <p style="color:#4b5563;line-height:1.6;margin-top:12px;">
    This report summarises key conservation metrics for ${speciesData.length} species.
    ${metrics.statusBreakdown.CR} are Critically Endangered, ${metrics.statusBreakdown.EN} Endangered, and ${metrics.statusBreakdown.VU} Vulnerable.
    Population trends indicate ${metrics.populationTrend.decreasingCount} species (${Math.round((metrics.populationTrend.decreasingCount / speciesData.length) * 100)}%) are in decline.
  </p>
</div>

<div class="section">
  <h2>Conservation Status Breakdown</h2>
  <table>
    <thead><tr><th>Status</th><th>Count</th><th>Percentage</th></tr></thead>
    <tbody>
      ${[
        ['Critically Endangered (CR)', metrics.statusBreakdown.CR],
        ['Endangered (EN)', metrics.statusBreakdown.EN],
        ['Vulnerable (VU)', metrics.statusBreakdown.VU],
        ['Near Threatened (NT)', metrics.statusBreakdown.NT],
        ['Least Concern (LC)', metrics.statusBreakdown.LC],
        ['Data Deficient (DD)', metrics.statusBreakdown.DD],
        ['Not Evaluated (NE)', metrics.statusBreakdown.NE],
      ].map(([label, count]) =>
        `<tr><td>${label}</td><td>${count}</td><td>${Math.round((count / speciesData.length) * 100)}%</td></tr>`
      ).join('')}
    </tbody>
  </table>
</div>

<div class="section">
  <h2>Species Included in Assessment</h2>
  <table>
    <thead>
      <tr>
        <th>Scientific Name</th>
        <th>Common Name</th>
        <th>IUCN Status</th>
        <th>Population Trend</th>
        <th>Observations</th>
      </tr>
    </thead>
    <tbody>
      ${speciesData.map(s => `
        <tr>
          <td><em>${escHtml(s.scientific_name)}</em></td>
          <td>${escHtml(s.common_name || '—')}</td>
          <td><span class="status-badge status-${s.iucn_status || 'NE'}">${s.iucn_status || 'NE'}</span></td>
          <td>${escHtml(s.population_trend || 'unknown')}</td>
          <td>${((s.observation_count || 0) + (s.gbif_occurrence_count || 0)).toLocaleString()}</td>
        </tr>
      `).join('')}
    </tbody>
  </table>
</div>

<div class="footer">
  DataWinder Multi-Species Conservation Report &bull; ${generatedAt}
</div>

</body>
</html>`;

    // Return the HTML directly so the frontend can offer a download or open in a new tab
    return new Response(html, {
      status: 200,
      headers: {
        'Content-Type': 'text/html; charset=utf-8',
        'Content-Disposition': `attachment; filename="${(report_name || 'conservation-report').replace(/[^a-zA-Z0-9-_]/g, '_')}.html"`,
      },
    });
  } catch (error) {
    console.error('Report generation error:', error);
    return Response.json({ error: error.message }, { status: 500 });
  }
});

function escHtml(str) {
  return String(str || '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function calculateMetrics(speciesData) {
  const metrics = {
    totalObservations: 0,
    statusBreakdown: { CR: 0, EN: 0, VU: 0, NT: 0, LC: 0, DD: 0, NE: 0, EX: 0, EW: 0 },
    populationTrend: { increasing: 0, stable: 0, decreasing: 0, unknown: 0, decreasingCount: 0 },
    dataGaps: 0,
  };

  speciesData.forEach(species => {
    metrics.totalObservations += (species.observation_count || 0) + (species.gbif_occurrence_count || 0);

    const status = species.iucn_status || 'NE';
    if (Object.prototype.hasOwnProperty.call(metrics.statusBreakdown, status)) {
      metrics.statusBreakdown[status]++;
    } else {
      metrics.statusBreakdown.NE++;
    }

    const trend = species.population_trend || 'unknown';
    if (trend === 'decreasing') {
      metrics.populationTrend.decreasing++;
      metrics.populationTrend.decreasingCount++;
    } else if (trend === 'stable') {
      metrics.populationTrend.stable++;
    } else if (trend === 'increasing') {
      metrics.populationTrend.increasing++;
    } else {
      metrics.populationTrend.unknown++;
    }

    if (!species.observation_count || species.observation_count === 0) {
      metrics.dataGaps++;
    }
  });

  return metrics;
}